### ISSUE TITLE
Compatibility with Cordova 6.0.0, Cordova iOS 4.0.1 and Cordova Android 5.1.0

### ISSUE THREAD

**Issue by bwhitty** [adnathan/ace#16]
Hi! I'm trying to integrate this into a [Meteor](http://meteor.com) application. I'm using a beta of their new 1.3 release which has upgraded their implementation to only support the versions of Cordova listed in the description.

When I try to add this plugin to a Meteor 1.3 app, I get a fatal error:

```
$ meteor run ios --port 4000
[[[[[ ~/dev/meteor/test-app ]]]]]

=> Started proxy.
% Failed to install 'cordova-plugin-ace':TypeError: Uh oh!
Object [object Object] has no method 'parse'
    at handlers.js-module.install (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:142:66)
    at Object.ActionStack.process (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Api.addPlugin (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/Api.js:205:20)
    at handleInstall (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:601:6)
    at /home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:385:28
    at _fulfilled (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
    at flush (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
=> Errors executing Cordova commands:

   While adding plugin cordova-plugin-ace@0.0.12 to Cordova project:
   TypeError: Uh oh!
   Object [object Object] has no method 'parse'
   at handlers.js-module.install
   (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:142:66)
   at Object.ActionStack.process
   (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
   at Api.addPlugin
   (/home/dir/dev/meteor/test-app/.meteor/local/cordova-build/platforms/android/cordova/Api.js:205:20)
   at handleInstall
   (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:601:6)
   at
   /home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:385:28
   at _fulfilled
   (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
   at flush
   (/home/dir/.meteor/packages/meteor-tool/.1.1.13-beta.11.1dw6vym++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
```

Are these versions of Cordova unsupported right now?

**Comment by adnathan** [comment]
I've now used Ace + Cordova 6.0 successfully (at least iOS). Sorry for the dumb question, but do you have instructions on how to install the 1.3 release of Meteor?

I'm not familiar with Meteor, but the error looks like something that wouldn't be specific to one plugin. Have you had success with this version of Meteor and a different plugin?

Thanks for any info you can provide!

**Comment by bwhitty** [comment]
No, thank you sir. To install Meteor: 

```
curl https://install.meteor.com/ | sh
```

To create a new (latest beta) project:

```
meteor create --release 1.3-beta.12 my-meteor-app
```

To add this plugin ass a cordova plugin:

```
meteor add cordova:cordova-plugin-ace@0.0.12
```

This may take extra setup on your machine, but to add ios as a platform and run the app as a cordova app on xcode's ios simulator:

```
meteor add-platform ios
meteor run ios-device
```

Probably good reference for this issue is that this is in reference to meteor/meteor#6356. Martijn Walraven is Meteor's cordova guru, so his comments could probably shed some light

**Comment by camrongodbout** [comment]
+1

**Comment by camrongodbout** [comment]
from other thread:

"I looked into this some more, and the issue seems to occur because cordova-plugin-ace uses path.parse(), which was only added in Node 0.12. Because Meteor runs in Node 0.10, this won't work until we upgrade the included Node version (which is next on the roadmap).

Until then, running cordova plugin add cordova-plugin-ace manually in the cordova-build directory is the only workaround, but you may have to do this again when the project is regenerated or when Meteor reinstalls the plugins (which happens every time you add/remove another plugin)." -Martijn Walraven

**Comment by bwhitty** [comment]
Yep, this is an issue with Meteor. Going to close this. Thanks!
