### ISSUE TITLE
Error in WebView.js (Android)?

### ISSUE THREAD

**Issue by efistokl** [adnathan/ace#26]
An attempt to do this:

```
new ace.WebView();
```

throws an error:

<pre> java.lang.RuntimeException: Unable to find a class named 'Windows.UI.Xaml.Controls.WebView'
                                                           at run.ace.IncomingMessages.create(IncomingMessages.java:50)
                                                           at run.ace.NativeHost$2.run(NativeHost.java:234)
                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:148)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
</pre>

min sdk level is 19
target sdk is 22
cordova version is 5.4.0

(My goal is to make a native WebView, insert it somewhere, and use it in the app)

Thank you for your attention!

**Comment by BreixoAM** [comment]
https://github.com/Microsoft/ace/issues/23

I think its solved in the last version.

**Comment by efistokl** [comment]
I've muddled through using that for android:

```
new ace.NativeObject('android.webkit.WebView');
```

and invoking native methods...
