### ISSUE TITLE
Not support for external/custom library ?

### ISSUE THREAD

**Issue by RockNHawk** [adnathan/ace#64]
Hello,

Ace is pretty cool!! I try to use it to build an customized hybrid app,but when I  and add an widget that defined in external jar into xaml

```
<StackPanel
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:ace="using:run.ace"
    xmlns:adx="using:android.support.design.widget" >

    <adx:TabLayout ></adx:TabLayout>

</StackPanel>
```

and android_sample.xml

```
<android.support.design.widget.TabLayout android:layout_width="match_parent" android:layout_height="60px">
        <android.support.design.widget.TabItem
            android:layout_width="40px"
            android:layout_height="match_parent"
            android:text="aaaa"/>
        <android.support.design.widget.TabItem
            android:layout_width="40px"
            android:layout_height="match_parent"
            android:text="bbbbb"/>
        <android.support.design.widget.TabItem
            android:layout_width="40px"
            android:layout_height="match_parent"
            android:text="cccc"/>
    </android.support.design.widget.TabLayout>
```

and add dependencies into build.gradle

```
dependencies {
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: 'CordovaLib', configuration: 'debug')
    releaseCompile project(path: 'CordovaLib', configuration: 'release')
    // SUB-PROJECT DEPENDENCIES END
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:support-v4:24.1.1'
    compile 'com.android.support:design:24.1.1'
}
```

but in both file, I get the runtime error:

```
Exception: Native error: java.lang.RuntimeException: Error in android.support.design.widget.TabLayout constructor: java.lang.RuntimeException: Failed to resolve attribute at index 0

    at run.ace.IncomingMessages.create(IncomingMessages.java:75)

    at run.ace.NativeHost$2.run(NativeHost.java:235)

    at android.os.Handler.handleCallback(Handler.java:739)

    at android.os.Handler.dispatchMessage(Handler.java:95)

    at android.os.Looper.loop(Looper.java:135)

    at android.app.ActivityThread.main(ActivityThread.java:5327)

    at java.lang.reflect.Method.invoke(Native Method)

    at java.lang.reflect.Method.invoke(Method.java:372)

    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)

    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)


See http://ace.run/docs/errors for help.
```

does ace supports external library and how to do it?

Thanks!

**Comment by RockNHawk** [comment]
It's ok,it'a android sdk API issue,not ace issue.
