### ISSUE TITLE
Update to cordova9 

### ISSUE THREAD

**Issue by anikinitek** [adnathan/ace#84]
Hi ,

  I am facing issue while adding this plugin . in cordova 9 . i can not downgrade to 8.1.2 . Because so many plugins are made for cordova 9 only. i need to lot of changes. please update this plugin for cordova 9 . i am facing below issue. 

**Issue1**
Failed to install 'cordova-plugin-ace': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (F:\Bus Taxy\BusTaxy\plugins\cordova-plugin-ace\src\plugin_hooks\after_plugin_install.js:57:21)
    at runScriptViaModuleLoader (C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

even i resolved this issue by doing some changes . while doing build i am getting below error. please help me to resolve  this issue

**Error while building after issue1 is resolved** 

ENOENT: no such file or directory, open 'F:\Bus Taxy\BusTaxy\platforms\android\AndroidManifest.xml'

![aceissue](https://user-images.githubusercontent.com/38279492/69803493-5267f280-1202-11ea-81a2-372c16b9beb6.PNG)

**Comment by Smokolisz** [comment]
I have the same issue, help is needed

**Comment by thirdwheel** [comment]
Do you have the same issue with this fork?

https://github.com/notsyncing/ace
